### PR TITLE
new documentation site

### PR DESCRIPTION
**Pull request by xuwei-k**
fix https://github.com/unfiltered/unfiltered/issues/353

see https://github.com/unfiltered/website and https://github.com/unfiltered/unfiltered.github.io

### CODE REVIEW

**Comment by omarkilani** [comment]
Awesome! 👍

**Comment by omarkilani** [comment]
Did we want to use unfiltered.ws as domain of GH pages?

https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by omarkilani** [comment]
You just have to do this:

https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/

And I can get it set up.

**Comment by xuwei-k** [comment]
> Did we want to use unfiltered.ws as domain of GH pages?

👍

**Comment by xuwei-k** [comment]
done

custom domain

**Comment by omarkilani** [comment]
I've updated DNS. Might take 10 minutes for TTL.

Could you please change docs URLs in the PR?

**Comment by xuwei-k** [comment]
> Could you please change docs URLs in the PR?

done

**Comment by omarkilani** [comment]
I've confirmed the custom domain is working.

unfiltered_ws

I had to change name servers for the domain to support ANAME on the domain apex. This is taking a little bit to propagate but it's almost done:

dns_prop

I'm merging and marking this as done.

**Pull request merged**
