### PR TITLE
Replace dispatch with okhttp3

### PR DESCRIPTION
**Pull request by hamnis**
o Remade most of the dispatch classic DSL
o Fixed some weird tests.
o Oauth 1 implemented using scribejava.

Shutting down the client on each request is pretty stupid, but I didnt try to change this behaviour.
We should rather have a BeforeAfter which does this.

I think this came out all right, and we should be able to move forward with #319 after this is merged.

### CODE REVIEW

**Comment by hamnis** [comment]
not sure why the netty ssl spec is failing.

**Comment by hamnis** [comment]
Might be related to #112

**Comment by xuwei-k** [comment]
> Might be related to #112

Let's use oraclejdk7 instead of openjdk7 https://github.com/unfiltered/unfiltered/pull/322

**Comment by xuwei-k** [comment]
👍  if rebased and travis passed

**Pull request merged**
