### PR TITLE
Upgrade unfiltered-jetty to jetty 9

### PR DESCRIPTION
**Pull request by n8han**
Let's do this with the same module name and a major version number increment for unfiltered. If the java 7 requirement is onerous to users of the module, we can resurrect jetty 8 in an `unfiltered-jetty8` module. (Let's wait for complaints before going to that trouble.)

This PR contains changes by Joni, Pasi, and myself.

### CODE REVIEW

**Comment by torbjornvatn** [comment]
Do you have an ETA for the 0.9.0 release? I could really need that Jetty9/Java8 support

**Comment by n8han** [comment]
Okay, could you test a beta before I release with the 0.9.0 version? It will be published shortly, as 0.9.0-beta1.

**Comment by n8han** [comment]
0.9.0-beta1 is published, I just tested with the basic template app and it worked fine. If you want to test right away you can get the artifacts direct from sonatype

```scala
resolvers ++= Seq(
  "sonatype" at "https://oss.sonatype.org/content/repositories/releases/"
)
```

**Comment by torbjornvatn** [comment]
We have used the 0.9.0-beta1 in production for months, so you can release at will :shipit:

**Comment by torbjornvatn** [comment]
Hi @n8han, any news on this release

**Pull request merged**
