### PR TITLE
ScalaTest example is slightly changed to fix compilation errors

### PR DESCRIPTION
**Pull request by mismatch**
Provided example is somewhat dated. I've stuck in compilation errors while trying to follow it. Changes are simple but not so evident. At least for such a newbie in Scala development as me (I'd known nothing about self-types till this day :) )

### CODE REVIEW

**Comment by chrislewis** [comment]
The tests are failing: https://travis-ci.org/unfiltered/unfiltered/builds/81590821

**Comment by mismatch** [comment]
Oh, I see but I have not clue how changes to README file could cause ChunkAggregatedUploadSpec failure. I would appreciate if you would help me with this failing test.

**Comment by chrislewis** [comment]
Apologies for that - I glanced at the pull and the build failure without looking at the diff!

**Comment by chrislewis** [comment]
Thanks!

**Comment by mismatch** [comment]
Thank you!

**Pull request merged**
